### ISSUE TITLE
Error Trying some examples.

### ISSUE THREAD

**Issue by andrewcz** [luisdamiano/BayesHMM#1]
Hi!
Really love the pacakge, looks awesome!
Im on an arch linux machine.

im getting an error -

![screenshot_2018-11-03_13-24-25](https://user-images.githubusercontent.com/2296335/47947174-9f2fba00-df6b-11e8-9ed7-c6dbcafe88be.png)

Thank you  @luisdamiano 

Best,
Andrew

**Comment by luisdamiano** [comment]
Hi Andrew, thanks for reporting the issue! I do know what is going on. I will fix namespaces soon and let you know.

**Comment by andrewcz** [comment]
Hi Luis!
Cheers! really like the project :).
Wanted to use it for a university assignment.
I was just wondering if the example 
http://past.rinfinance.com/agenda/2018/LuisDamiano.pdf
is located somewhere in the repo.
Best,
Andrew

**Comment by luisdamiano** [comment]
Andrew,

I just pushed an update fixing namespaces. I ran the file ./inst/examples/hmm-univariate-gaussian.R and it works out of the box. This was mostly my fault for pushing a half-baked commit. If you use BayesHMM for your assignment, please let me know once you're done with it and I'll close the issue. I'd rather keep it open in case you have more technical problems. [This vignette](https://luisdamiano.github.io/BayesHMM/articles/introduction.html) should give you some ideas on how to use the package, but I do recognize that our documentation is very lacking at this point (I'm currently working on this when life allows). Also, [this article](https://github.com/luisdamiano/BayesHMM/blob/master/vignettes/introduction2.Rmd) is supposed to be more detailed but I'm only halfways. Finally, you shouldn't need to load rstan unless you want to call functions from it. That may (or may not) cause problems by masking methods.

The R/Finance model was not built using BayesHMM. Instead, it was based on the code and dataset available [in this other public repo](https://github.com/luisdamiano/gsoc17-hhmm/tree/master/tayal2009). Bare in mind that the model is quite complex from a computational point of view, so we had to resource to MAP estimates with several random initializations. Definitely not the most elegant of my projects!

Cheers,

Luis.

**Comment by andrewcz** [comment]
@luisdamiano so informative!!
thank you for your help!
really appreciate it :)
will give it a try.
Best,
Andrew

**Comment by luisdamiano** [comment]
Hi Andrew,

I'd like to close the issue if have no further questions. Also, make sure you check the our last version, functions are fully documented and we've added several unit tests.

**Comment by andrewcz** [comment]
Hi @luisdamiano !
Thank you so much for your help!
The project is not due till June of next year.
I'm going to keep experimenting with the project till then but the new version 
looks awesome.
Many thanks,
Best,
Andrew
